### ISSUE TITLE
Incorporate feedback into TOC geographic analysis

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/planning-entitlements#23]
04-28-2020 presentation at Housing Policy Standing Meeting (PMU, Housing Unit & GIS teams)

* Check if Orange and Silver Lines are included
* Exclude rail stations and TOC tiers that fall outside City of LA. Don't want this to be included in the denominator, the area that is eligible for TOC, and there are no entitlements happening.
* Regional Connector won’t see TOC entitlements because there are other policies in place that supersede TOC program, and those have better developer benefits, so they wouldn’t use TOC program.

**Comment by ian-r-rose** [comment]
A few in-line comments on these TODOs:

>     * Check if Orange and Silver Lines are included

They are included, see [here](https://github.com/CityOfLosAngeles/planning-entitlements/blob/f9f072aa4cc35035de08ea2fa3f7ed79253884ae/notebooks/toc.py#L590-L599)

> 
>     * Exclude rail stations and TOC tiers that fall outside City of LA. Don't want this to be included in the denominator, the area that is eligible for TOC, and there are no entitlements happening.
>

We already filter for tiers that don't intersect the City of LA, see the `clip` argument in the `toc.py` functions. We could further remove the partially overlapping parts of tiers on the boundary, which would change the denominator slightly.
