### ISSUE TITLE
clip shapefiles at LA city boundary 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/planning-entitlements#26]
for all the shapefiles / maps, clip the LA boundary so not as to show potential TOC areas in BH, east los, etc 

For station counts, make sure that the station + radius intersects the city of LA before counting (ie count 26th in SM, don't count Azuza Gold Line Station.

**Comment by hunterowens** [comment]
broken out from #23 so I can take a pass at this

**Comment by ian-r-rose** [comment]
The second part we already do, the first part we do not

**Comment by ian-r-rose** [comment]
Unless I misunderstand what you mean? I am referring to [this](https://github.com/CityOfLosAngeles/planning-entitlements/blob/f9f072aa4cc35035de08ea2fa3f7ed79253884ae/notebooks/toc.py#L544-L548)
