### ISSUE TITLE
determine what zoning rules need to be interpreted

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/planning-entitlements#3]
need to determine which rules from a zoning code are useful for analysis

for example 

* height 
* FAR 
* parking 

@tiffanychu90 to add

**Comment by tiffanychu90** [comment]
* Height, setbacks, density, FAR, everything on Table 2. 
* Theoretical density vs practical/functional density once all zoning rules applied. 

Steps:
1. Parse the zoning string. Build and improve parser in #5, #6, #9.
2. Crosswalk of the rules 
3. Find deltas in entitlements. Ex: on average, they want to reduce the front setback by 2 ft, rear setback by 1 ft.

**Comment by hunterowens** [comment]
@tiffanychu90 can we close this?

**Comment by tiffanychu90** [comment]
Close via #5, #6, #9, and #10 for zoning and PCTS parsers needed.

But, need to reopen new issue to address a future question on finding the deltas in entitlements.
