### ISSUE TITLE
Fix Census cleaning

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/planning-entitlements#33]
* Fix some of the cleaning done for Census in spitting out pct and num columns. Some tables have var_type = "number" and var_type = "percent" remaining. Weird outputs when reshaping later.
* Either drop var_type or check if this reflects underlying errors in the cleaning

**Comment by tiffanychu90** [comment]
@ian-r-rose: notebooks/07-toc-census-stats.ipynb now also includes stats for tracts with TOC entitlements.
Parquet file to compare: s3://city-planning-entitlements/data/final/census_tract_stats.parquet
* toc_area, toc_AIN, toc_ENT are the columns used to split tracts into TOC vs Non-TOC

Still getting that median incomes for TOC tracts are lower than non-TOC tracts, even when just looking at tracts with TOC entitlements.

**Comment by ian-r-rose** [comment]
> Still getting that median incomes for TOC tracts are lower than non-TOC tracts, even when just looking at tracts with TOC entitlements.

I don't think this is necessarily in conflict with TOC entitlement requests being positively correlated with income.

**Comment by tiffanychu90** [comment]
> > Still getting that median incomes for TOC tracts are lower than non-TOC tracts, even when just looking at tracts with TOC entitlements.
> 
> I don't think this is necessarily in conflict with TOC entitlement requests being positively correlated with income.

Ok. Can you double-check the 07 notebook for the aggregations when you get a chance? Btw, I swapped out the race table...now it's % non-Hispanic white...I could calculate the % non-white, but just haven't.

@hunterowens Is the race/ethnicity table B01001? That's the one you used in notebook-demos.

**Comment by tiffanychu90** [comment]
@ian-r-rose All right, median hh income for just 2 groups (has TOC ENT vs no TOC ENT) results in lower incomes associated with TOC tracts. But, when you look at # of TOC ENT, there's some variability there. Particularly, 2 tracts with lots of TOC ENT (11 or more), they have high median incomes.

**Comment by tiffanychu90** [comment]
Close via #35
