### ISSUE TITLE
Parent cases function

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/planning-entitlements#41]
Optimize function for grabbing PCTS data with optional parameters of start/end date, prefix/suffix lists done in #40.
This function should be used whenever PCTS is used for analysis, and standardizes initial data cleaning, dropping child cases, but allowing parent cases to inherit all the child cases' prefixes/suffixes.

Now, think about how to fold in identifying parent cases to a function. When PCTS moves off of being a static backup, these cases aren't static anymore. Parent cases and child case histories should all be identified in a follow-up function so that whenever the main function is called, it returns a list of parent cases and lots of prefix/suffix dummy variables.

Figure out:
* Valid prefixes that don't appear in any cases, but are valid: HPO, PS, TT, VTT. Right now, they're created and hold 0's.
* Values that appear as prefixes in CASE_NBR but are actually suffixes: CUB, EIR, CUZ. Prefix-suffix dummies might be 0-1, 1-0, or 1-1, but we only want 1 suffix dummy in the end, with 1 flagged if either prefix/suffix is 1.
* How do we incorporate the above 2 when the args for prefix/suffix lists might not contain HPO or EIR? When arg is `None` or if those are requested, we definitely want to spit those out. But if some other list is included, these would naturally be excluded.
* Would it be faster to do the `pd.melt` ahead of time? Think about where to spit out a long df, either as a sub-function, or somewhere, if it helps speed things up.

**Comment by ian-r-rose** [comment]
> Optimize function for grabbing PCTS data with optional parameters of start/end date, prefix/suffix lists done in #40.
> This function should be used whenever PCTS is used for analysis, and standardizes initial data cleaning, dropping child cases, but allowing parent cases to inherit all the child cases' prefixes/suffixes.
👍  

> Now, think about how to fold in identifying parent cases to a function. When PCTS moves off of being a static backup, these cases aren't static anymore. Parent cases and child case histories should all be identified in a follow-up function so that whenever the main function is called, it returns a list of parent cases and lots of prefix/suffix dummy variables.

Agree with the above. I don't *love* having so many dummy variables, but it's simple enough to melt later if need be.

> Figure out:
> 
>     * Valid prefixes that don't appear in any cases, but are valid: HPO, PS, TT, VTT. Right now, they're created and hold 0's.
Seems good for the moment. I wonder if there is a way to tell `get_dummies` to produce those automatically.

>     * Values that appear as prefixes in CASE_NBR but are actually suffixes: CUB, EIR, CUZ. Prefix-suffix dummies might be 0-1, 1-0, or 1-1, but we only want 1 suffix dummy in the end, with 1 flagged if either prefix/suffix is 1.

Tricky. As long as there is no overlap between prefixes and suffixes, it should be doable though, right?

>     * How do we incorporate the above 2 when the args for prefix/suffix lists might not contain HPO or EIR? When arg is `None` or if those are requested, we definitely want to spit those out. But if some other list is included, these would naturally be excluded.
> 
>     * Would it be faster to do the `pd.melt` ahead of time? Think about where to spit out a long df, either as a sub-function, or somewhere, if it helps speed things up.

Yeah, not sure! There are cases where both are useful. For the regression stuff, long form has been more useful.

**Comment by ian-r-rose** [comment]
>     * Valid prefixes that don't appear in any cases, but are valid: HPO, PS, TT, VTT. Right now, they're created and hold 0's.
This is done here: https://github.com/CityOfLosAngeles/planning-entitlements/blob/713b646b42172b1ffeac64f6890fd07625399a43/notebooks/pcts_census_utils.py#L285-L308

Note that some of these prefixes *do* actually appear, but seem to have malformed PCTS strings which fail to parse.

>     * Values that appear as prefixes in CASE_NBR but are actually suffixes: CUB, EIR, CUZ. Prefix-suffix dummies might be 0-1, 1-0, or 1-1, but we only want 1 suffix dummy in the end, with 1 flagged if either prefix/suffix is 1.


Done here: https://github.com/CityOfLosAngeles/planning-entitlements/blob/713b646b42172b1ffeac64f6890fd07625399a43/notebooks/pcts_census_utils.py#L310-L318
>     * How do we incorporate the above 2 when the args for prefix/suffix lists might not contain HPO or EIR? When arg is `None` or if those are requested, we definitely want to spit those out. But if some other list is included, these would naturally be excluded.

I think it would be better to be explicit about what prefix/suffixes to exclude, and default to return all of them. I think the above functions are pretty general.

>     * Would it be faster to do the `pd.melt` ahead of time? Think about where to spit out a long df, either as a sub-function, or somewhere, if it helps speed things up.

Skipping any `pd.melt` for now, I think it's working okay at the moment

**Comment by ian-r-rose** [comment]
Fixed by #45
