### ISSUE TITLE
move TOC to LA plan

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/planning-entitlements#48]
`toc.py` should be move into the LAPlan library

**Comment by tiffanychu90** [comment]
Maybe in the much, much future. I don't see a real need for this. The functions in `toc.py` are quite complicated, go through cleaning functions within a notebook to standardize the dataframes across Metro Rail/Metro Bus/Metrolink, have multiple geometry columns, which make storage tricky, and are only used in 1-2 notebooks.

**Comment by tiffanychu90** [comment]
Made sure `toc.py` functions are updated to match the latest `geopandas` with @ian-r-rose
