### ISSUE TITLE
Redo / Cleaning of existing notebooks 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/planning-entitlements#49]
w/ the existence of the new `laplan` library, I think it makes sense for the authors of each notebook to take a look an update to use the new functions and remove vestigial cleaning code / functionality so we all rely on the same methods.

**Comment by hunterowens** [comment]
ideally, this should cut down on some of the merge conflicts /chaos / disagreement over what exactly each chart shows.

**Comment by tiffanychu90** [comment]
#46, #51
