### ISSUE TITLE
"setup.py" not found for laplan

### ISSUE THREAD

**Issue by trantom** [CityOfLosAngeles/planning-entitlements#50]
Running into this error during `docker-compose build` after #46 :

```
Step 5/5 : RUN pip install -r /tmp/requirements.txt
 ---> Running in 4fb999c7d01e
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /root/work
ERROR: Service 'lab' failed to build: The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1
```

Managed to fix it by copying over laplan with two lines in Dockerfile before the pip install since the `requirements.txt` is having pip install with option -e for local package installation.  It didn't see it in WORKDIR /root/work in the container it was setting up for the `lab` service in docker-compose using the `citywide-civis-lab:497b06e9b88f ` image.  Let me know if it's an issue on my end.

```
COPY laplan ./laplan
COPY setup.py .

RUN pip install -r /tmp/requirements.txt
```

**Comment by ian-r-rose** [comment]
Thanks @trantom, you are absolutely correct, I messed this one up. Care to make a PR with this fix?

**Comment by ian-r-rose** [comment]
Alternatively (and I have been experimenting with this in voila), we can include `/app` in our `PYTHONPATH`. I generally think it's a bad idea to set that environment variable, but this might be a valid use-case.

**Comment by trantom** [comment]
Thanks for providing both options @ian-r-rose.  While it may be a valid use-case for the second option if you generally think it's a bad idea we can stick with the more verbose option for now until a better approach calls for a change.  I think I might prefer not adding `/app` to `PYTHONPATH` as well since it makes the `requirements.txt` not necessary unless I am thinking about this incorrectly.  I'll make a PR for it.

**Comment by ian-r-rose** [comment]
Part of the reason I like the second case is that it could also cover the dashboard deployment that we have been showing. A related third option would be to sniff for a  `setup.py` and install if it finds it.

**Comment by ian-r-rose** [comment]
Related fix for the dashboard-deployment use case in CityOfLosAngeles/aqueduct#345. @trantom I think your suggested fix is still the correct one for local development

**Comment by trantom** [comment]
@ian-r-rose I'm not so familiar with the dashboard deployment use case, but if it is an option that provides more flexibility moving forward I can remove my current pull request and we can do the add to `PYTHONPATH` option.  Would we specify an ENV in the Dockerfile to add it?
