### ISSUE TITLE
Validate against PCTS reporting module / use historical list of AINs

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/planning-entitlements#58]
Planning uses this PCTS reporting module on the intranet: http://161.149.135.156:8086/  

Suffixes to check: ADU, SPR
* SPR: no child cases using the date range 1/1/10 - 10/31/19, we get 809 entries compared to the 454 in D1

Do deep dive to see how many we filter out based on suffix exclusions, outliers, etc.

**Comment by tiffanychu90** [comment]
Possibly we are missing AINs because we are using AINs from 2019. Switch to [2006-2019 parcels](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2006-thru-2019/9trm-uz8i). Need to identify, based on parcel centroids, all the possibly AINs that belong to a given parcel polygon.

**Comment by ian-r-rose** [comment]
> Need to identify, based on parcel centroids, all the possibly AINs that belong to a given parcel polygon.

Do we need to do this? That parcels dataset doesn't include polygons, just centroids.

**Comment by tiffanychu90** [comment]
Switching to 2006-2019 parcels means only centroids.

Possibly do a spatial join against a parcel file with polygons...but remains iffy, what happens if different centroids fall within the same polygon? Not sure how to handle this. 

To add into / overwrite crosswalk_parcels_tracts:

- [x]  duplicate parcels (`num_AIN`)
- [x]  census tract (`GEOID`)
- [x]  TOC Tier (`TOC_Tier`), spatial join parcel centroids to TOC_Tiers
- [x]  total number of AIN in tract, with duplicates removed (`total_AIN`)
- [x]  if over 50% of the parcels is within any TOC tier, then tract is considered TOC-eligible (`toc_AIN`)
- [ ]  individual parcel's area and sum of parcel area within tract (`parcel_sqft`, `parcel_tot`), only if parcel polygons are used
- [ ]  if over 50% of the area, sum of `parcel_sqft` is within any TOC tier, then tract is considered TOC-eligible (`toc_area`), only if parcel polygons are used
- [x]  update `data-workflow-notes` and `scripts_notebooks_README` accordingly

**Comment by tiffanychu90** [comment]
Validate against PCTS in #55, #57.
Switch to historical AINs in #59

**Comment by tiffanychu90** [comment]
Will roll the `laplan.pcts.subset_pcts` logic back to previous version, where if any of the allowed prefix/suffix are in the case string, keep the case in, even if part of case string contains excluded prefix/suffix. Only standalone cases of excluded prefix/suffix will be excluded. This should get the counts much closer to Planning reporting module.

**Comment by tiffanychu90** [comment]
Update `laplan.pcts.subset_pcts`, use new parcels crosswalk, update D1, regressions in #61
