### ISSUE TITLE
Prefixes being dropped due to subsetting and different case string formats

### ISSUE THREAD

**Issue by trantom** [CityOfLosAngeles/planning-entitlements#60]
`laplan.pcts.subset_pcts()` may be dropping prefixes as it is using the `GENERAL_PCTS_RE` regular expression pattern.

We'll get outputs such as
`Prefixes with no associated cases: {'VTT', 'TT', 'HPO', 'PS'}`
due to different PCTS case string formats such as VTT and TT possibly only having a number following the dash.  Perhaps the MISSING_YEAR_RE can be used for these cases.
Some examples:
TT-68593-CC-M1
TT-71244-CN
TT-47987

I'll work on finding out about the string formats.  Let me know if this is something that was looked into before and I'm overlooking something or if those prefixes are not of interest.

**Comment by tiffanychu90** [comment]
@trantom Do you want to do a PR that adds an additional step to the PCTS parser to catch the VTT/TT cases that failed to parse? An example can be found for the [zoning parser](https://github.com/CityOfLosAngeles/planning-entitlements/blob/master/laplan/zoning.py), where there's a fallback function if the first attempt failed.

**Comment by trantom** [comment]
@tiffanychu90 I can give it a go.  Thanks for the reference I'll give that a look.  Although the cases with those certain prefixes are being dropped in [`subset_pcts()` ](https://github.com/CityOfLosAngeles/planning-entitlements/blob/master/laplan/pcts.py#L270 )so are we implementing it within that function or did you want to try to write another internal function for the[ `PCTSCaseNumber` dataclass](https://github.com/CityOfLosAngeles/planning-entitlements/blob/master/laplan/pcts.py#L200) similar to that fallback function in the zoning parser?

**Comment by ian-r-rose** [comment]
@trantom Yes, I think it would be appropriate to do it in `subset_pcts()`.

We have backed off of using the dataclass a bit for performance reasons. Using pandas regex matching is much faster when you are cranking through a larger number of cases, so I think we should use that again, but with the alternative regex for the cases that fail to parse with the first one.

**Comment by tiffanychu90** [comment]
Use the back-up regex for parsing PCTS as follow-up after initial regex doesn't parse the VTT/TTs

VTTs have different pattern for case string (applies to subdivisions). Pre-2010, case strings didn't have year anyway.

**Comment by trantom** [comment]
Work done with #63
