### ISSUE TITLE
Figure out delivery to PowerBI

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/planning-entitlements#70]
We have a number of data pipelines that we would like to allow PMU to self-serve. We should find a suitable format for them to point power BI at (CSV? Shapefile? JSON?), and where to put it (S3?)

**Comment by trantom** [comment]
PowerBI has multiple connectors including SQL Server which we do have.  Maybe that can be an automated loading.  Though that will depend on complications we may encounter that the systems group can tell us about.

The tradeoff is that they won't freely be able to manipulate their data, but that is why DAX and the ETL functions in PowerBI exist.

**Comment by tiffanychu90** [comment]
Can PowerBI read from S3? 

I'm more inclined toward options where we can use 99% of the work we've already done, but change a couple lines to where it exports to and to schedule it. 

I'm less inclined toward rewriting the same process in DAX.

**Comment by trantom** [comment]
Yes it is possible based on a cursory search, but it is not as easy as a direct connection and not only that setting up a connection to S3 might need some requests from an AWS admin for that bucket.  If a flat file is really desired maybe something could be set up on a machine or VM over in planning to be able to run the scripts and have it be dropped off to a shared network folder.  I feel like Hunter would have some good input on this as he been corresponding with Mony and David Terukina.

Either way is a trade-off though it's either there is more work front-loaded for your team or back-loaded for PMU and systems.

As for DAX I meant that if they wanted to further manipulate from what the scripts and processing from this project has done in any way.  We wouldn't need to do anything with DAX.

**Comment by tiffanychu90** [comment]
@hunterowens

**Comment by tiffanychu90** [comment]
@hunterowens and @trantom have tested this to make sure it works
